### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by davewasmer** [ImTheSquid/gst-ximageredux#1]
Hey @ImTheSquid :wave: interesting project! Just ran into `ximagesrc` crashing during resize, and ran across this project while researching the crash - seems like exactly the solution!

I'm relatively new to gstreamer, so apologies for the newbie question, but what's the process to reference this as an element in my pipeline? The crate doesn't seem to ship with any binaries - do I need to compile from source?

**Comment by ImTheSquid** [comment]
Yeah, just clone to repo and `cargo build --release`, that should put a library file in the build output directory. Once you do that, add that library to your gstreamer load path and it should work. Thanks for opening this, I'll put this in the README.
